# Generated by Django 2.0.2 on 2018-03-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumbnile',
            field=models.ImageField(blank=True, default='defualt.png', upload_to=''),
        ),
    ]
